# Generated by Django 2.1.5 on 2019-02-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='about me'),
        ),
    ]
