# Generated by Django 2.1.5 on 2019-02-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190216_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
